### ISSUE TITLE
[Feature Request] Emulate Joy-Con

### ISSUE THREAD

**Issue by Caustle** [kenesu-h/sys-hidplus-client-rs#4]
I have been using this with Parsec to play with co-op games with my long-distance girlfriend; it has been great. However, there are certain co-op games that require split joy-cons instead of 2 separate pro-controllers. Could this be an added feature? I think the original sys-hid client had this feature.

**Comment by kenesu-h** [comment]
Hey Caustle! This actually is a thing, but there's a few catches.

One thing is that it's just that I didn't get around to making it accessible on the GUI, but there _is_ a setting for it, it's just stuck behind [the command line](https://github.com/kenesu-h/sys-hidplus-client-rs/blob/1.1.0-alpha/docs/setup.md#command-line-3) or manually editing the config. It's been a while, but you should be able to change the config file to set specific controller slots to be split joy-cons. I know it's kinda confusing, but I don't want to be more verbose or text-heavy than I already am, so I'll be more than happy to go more in-depth if needed.

The other catch is that full split joy-con support stopped being a possible thing period, last I heard. I haven't checked if that's actually still the case, but the original sys-hidplus dev sent me this [issue](https://github.com/switchbrew/libnx/issues/567) that basically says you can't use SL/SR, and it doesn't look like that's been addressed ever since.

Plus... my motivation (for sys-hidplus at least) has been really on-and-off. I could definitely try to make that setting easier to access with the GUI, but tbh I made a lot of bad design choices back when I was actively working on this lol. Either way, hope that helps a bit, and like I said, I'm more than willing to help change that setting via the command line/editing the config.

**Comment by Caustle** [comment]
Wow, I just want to preface by saying thank you for the hasty clarification and detailed reply; I really appreciate the work you and the original sys-hid dev placed into the project. Using your GUI is much simpler to get things set-up so there's no time wasted. My girlfriend and myself recently started doing long-distance, and this project has really helped our relationship immensely, you have no idea the gratitude I have for both of you. (The GUI is more than sufficient for what I needed it for, so don't be too hard on yourself)

I just read up on what you sent, bummer that the system masks those input out (no support for SL/SR, is detrimental to most joy-con games); I guess if PC emulators can emulate joy-cons, I might have to resort to using emulation for those games then. Thank you so much again, I hope you all the best for your future endeavours!

**Comment by kenesu-h** [comment]
Thanks to you too! As for PC emulators, I actually just took time to check Yuzu and Ryujinx - they both allow you to map your controllers to single joy-cons. I couldn't really speak as to which emulator is better since it's been a while since I tried to use either, but emulators should totally be an option!
